# ALP - DATA WAREHOUSE                                                                                                                                                            EXTRACT, TRANSFORM, LOAD

## Group 3
### Jefferson Wesley Liunardi (0706022310046) 
### Richo Ivan Ardiyanto (070602231007)
### Rio Mulyawan (0706022310056)
### Valentyno Marcel Gunawan (0706022310029)

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Path to the file
file_path = r"c:\Users\ASUS\Desktop\College\Semester 4\Data Warehouse\ALP Data Warehousing\customer_churn.xlsx"

# Extract the data from the Excel file
df = pd.read_excel(file_path)

# Check the first few rows of the dataset to verify it's loaded correctly
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [4]:
# Check for missing values
missing_values = df.isnull().sum()
print(missing_values)

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [ ]:
# Step 2: Convert 'Total Charges' to numeric (handle non-numeric values)
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7032 non-null   float64
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(6), object(23)
memory usage: 1.8+ MB

In [7]:
# Check unique values in 'Churn Reason' column
print(df['Churn Reason'].unique())

['Competitor made better offer' 'Moved' 'Competitor had better devices'
 'Competitor offered higher download speeds'
 'Competitor offered more data' 'Price too high' 'Product dissatisfaction'
 'Service dissatisfaction' 'Lack of self-service on Website'
 'Network reliability' 'Limited range of services'
 'Lack of affordable download/upload speed' 'Long distance charges'
 'Extra data charges' "Don't know" 'Poor expertise of online support'
 'Poor expertise of phone support' 'Attitude of service provider'
 'Attitude of support person' 'Deceased' nan]

In [8]:
# Fill missing values in the 'Churn Reason' column with 'Unknown'
df['Churn Reason'] = df['Churn Reason'].fillna('Unknown')

# Verify if missing values are handled
print(df.isnull().sum())

CustomerID            0
Count                 0
Country               0
State                 0
City                  0
Zip Code              0
Lat Long              0
Latitude              0
Longitude             0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Label           0
Churn Value           0
Churn Score           0
CLTV                  0
Churn Reason          0
dtype: int64

In [10]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

# CREATE DIMENSION TABLE

In [28]:
# Create Dim_Customer with corrected column names
dim_customer = df[['CustomerID', 'Gender', 'Senior Citizen', 'Partner', 'Dependents']].drop_duplicates()

# Save Dim_Customer to a CSV file
dim_customer.to_csv('dim_customer.csv', index=False)

# Display Dim_Customer
dim_customer.head()

   CustomerID  Gender Senior Citizen Partner Dependents
0  3668-QPYBK    Male             No      No         No
1  9237-HQITU  Female             No      No        Yes
2  9305-CDSKC  Female             No      No        Yes
3  7892-POOKP  Female             No     Yes        Yes
4  0280-XJGEX    Male             No      No        Yes

In [42]:
# Add unique LocationID for customers
df['LocationID'] = df['Zip Code']

# Customer Demographics Dimension
dim_location = df[['LocationID', 'Country', 'State', 'City']].drop_duplicates()

# Save to CSV
dim_location.to_csv('dim_location.csv', index=False)

# Display only the contents of the dim_location dimension
dim_location.head()

   LocationID        Country       State         City
0       90003  United States  California  Los Angeles
1       90005  United States  California  Los Angeles
2       90006  United States  California  Los Angeles
3       90010  United States  California  Los Angeles
4       90015  United States  California  Los Angeles

In [ ]:
# Add unique LocationID for customers
df['LocationID'] = df['Zip Code']

# Payment Method and Billing Preferences Dimension
dim_payment_method = df[['LocationID', 'Payment Method', 'Paperless Billing']].drop_duplicates()

# Save to CSV
dim_payment_method.to_csv('dim_payment_billing_dim.csv', index=False)

# Display only the contents of the dim_payment_method dimension
dim_payment_method.head()

   LocationID             Payment Method Paperless Billing
0       90003               Mailed check               Yes
1       90005           Electronic check               Yes
2       90006           Electronic check               Yes
3       90010           Electronic check               Yes
4       90015  Bank transfer (automatic)               Yes

In [ ]:
# Mapping unique combinations of Contract to numeric IDs
contract_mapping = {
    'Month-to-month': 10,
    'One year': 14,
    'Two year': 18
}

# Combining the Contract column to create combinations
df['Contract_Payment'] = df['Contract']

# Mapping the combinations to ContractID using the predefined mapping
df['ContractID'] = df['Contract_Payment'].map(contract_mapping)

# Saving only the Contract and ContractID columns to a CSV file named contract.csv
df[['Contract', 'ContractID']].to_csv('dim_contract.csv', index=False)

# Displaying only the Contract and ContractID columns
df[['Contract', 'ContractID']].head()

         Contract  ContractID
0  Month-to-month          10
1  Month-to-month          10
2  Month-to-month          10
3  Month-to-month          10
4  Month-to-month          10

In [36]:
import pandas as pd

# Define the mapping for services to numeric values
service_mapping = {
    'Yes': 1, 'No': 0,
    'DSL': 'D', 'Fiber optic': 'F', 'Cable': 'C',
    'None': 0  # For cases where the service is not available
}

# Function to convert a service value to its numeric equivalent or a default value
def map_service(value):
    return service_mapping.get(value, 2)  # Default to '2' for unknown or missing services

# Apply the service mapping for the relevant columns and create the ServiceID
service_columns = [
    'Phone Service', 'Multiple Lines', 'Internet Service', 'Online Security',
    'Online Backup', 'Device Protection', 'Tech Support'
]

df['ServiceID'] = df[service_columns].fillna('None').applymap(map_service).astype(str).agg(''.join, axis=1)

# Create the service dimension table by selecting distinct rows and writing to CSV
dim_service = df[['ServiceID'] + service_columns].drop_duplicates()

# Save the resulting DataFrame to a CSV file
dim_service.to_csv('dim_service.csv', index=False)

# Display the first few rows of the resulting 'dim_service' DataFrame
dim_service.head()

C:\Users\richo\AppData\Local\Temp\ipykernel_23220\3309653533.py:20: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df['ServiceID'] = df[service_columns].fillna('None').applymap(map_service).astype(str).agg(''.join, axis=1)

,ServiceID,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support
0,10D1100,Yes,No,DSL,Yes,Yes,No,No
1,10F0000,Yes,No,Fiber optic,No,No,No,No
2,11F0010,Yes,Yes,Fiber optic,No,No,Yes,No
3,11F0011,Yes,Yes,Fiber optic,No,No,Yes,Yes
4,11F0110,Yes,Yes,Fiber optic,No,Yes,Yes,No

In [ ]:
# Combining the services owned by customers into one column
df['ServicePackage'] = df['Phone Service'] + '_' + df['Internet Service'] + '_' + \
                       df['Online Security'] + '_' + df['Online Backup'] + '_' + \
                       df['Device Protection'] + '_' + df['Tech Support'] + '_' + \
                       df['Streaming TV'] + '_' + df['Streaming Movies']

# Creating a unique ID for each service package
df['ServicePackageID'] = df['ServicePackage'].astype('category').cat.codes

# Creating the Service Package dimension that includes ServicePackageID and the service combinations
dim_service_package = df[['ServicePackageID', 'ServicePackage', 'Streaming TV', 'Streaming Movies']].drop_duplicates()

# Saving the Service Package dimension to CSV
dim_service_package.to_csv('dim_service_package.csv', index=False)

# Displaying the Service Package dimension
print(dim_service_package.head())

   ServicePackageID                         ServicePackage Streaming TV  \
0               112            Yes_DSL_Yes_Yes_No_No_No_No           No
1               128      Yes_Fiber optic_No_No_No_No_No_No           No
2               139   Yes_Fiber optic_No_No_Yes_No_Yes_Yes          Yes
3               143  Yes_Fiber optic_No_No_Yes_Yes_Yes_Yes          Yes
4               155  Yes_Fiber optic_No_Yes_Yes_No_Yes_Yes          Yes

  Streaming Movies
0               No
1               No
2              Yes
3              Yes
4              Yes

In [34]:
fact_churn = df[['CustomerID', 'Tenure Months', 'Monthly Charges', 'Total Charges', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason', 'ContractID', 'LocationID', 'ServiceID','ServicePackageID']].drop_duplicates()
fact_churn.to_csv('fact_churn.csv', index=False)
fact_churn.head()

,CustomerID,Tenure Months,Monthly Charges,Total Charges,Churn Value,Churn Score,CLTV,Churn Reason,ContractID,LocationID,ServiceID,ServicePackageID
0,3668-QPYBK,2,53.85,108.15,1,86,3239,Competitor made better offer,10,90003,10D1100,112
1,9237-HQITU,2,70.70,151.65,1,67,2701,Moved,10,90005,10F0000,128
2,9305-CDSKC,8,99.65,820.50,1,86,5372,Moved,10,90006,11F0010,139
3,7892-POOKP,28,104.80,3046.05,1,84,5003,Moved,10,90010,11F0011,143
4,0280-XJGEX,49,103.70,5036.30,1,89,5340,Competitor had better devices,10,90015,11F0110,155